config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show', id: 'home'
  match 'for/:id' => 'portals#route', as: :portal_router, via: :all

  devise_for :users
  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/monitor', as: :monitor
  end

  authenticate :user do
    resources :replies
    resources :submissions
    resources :destinations
    resources :portals
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :destination
  belongs_to :submission

  scope :failed, -> { where('http_status_code >= ?', 400) }
  scope :successful, -> { where('http_status_code < ?', 400) }

  after_create   :increment_counters_on_submission
  before_destroy :decrement_counters_on_submission

  serialize :headers, JSON

  def successful?
    http_status_code < 400
  end

  def failed?
    http_status_code && http_status_code.to_i >= 400
  end
  alias :failure? :failed?

  def pending?
    new_record? || http_status_code.blank?
  end

  def status
    matched = %w(pending successful failed).detect{ |key| send("#{key}?") }
    matched ? matched.to_sym : :unknown
  end

  def http_status_message
    Rack::Utils::HTTP_STATUS_CODES[http_status_code]
  end

  def self.for(submission, destination)
    find_or_initialize_by(
      submission_id:  submission.id,
      destination_id: destination.id
    )
  end

  def self.for(submission, destination)
    find_or_initialize_by(
      submission_id:  submission.id,
      destination_id: destination.id
    )
  end

  private

  def increment_counters_on_submission
    column = successful? ? :successful_replies_count : :failed_replies_count
    Submission.increment_counter(column, submission_id)
  end

  def decrement_counters_on_submission
    column = successful? ? :successful_replies_count : :failed_replies_count
    Submission.decrement_counter(column, submission_id)
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_card.html.erb
<!--
<pre><code><%= reply.headers.map{|k,v| "#{k.titleize.gsub(/\s+/, '-')}: #{v}" }.join("\n") if reply.headers.present? %>

<%= reply.body %></code></pre>
-->

<div class="panel panel-<%= reply.status_style %> replyCard" data-id="<%= reply.id %>">

  <div class="panel-heading" data-toggle="collapse"
    data-parent="#submissionOverview-<%= reply.submission.id %>"
    data-target=".replyCard[data-id='<%= reply.id %>'] .panel-body">
    <%= reply.destination.url %>
  </div>

  <div class="panel-body collapse out">
    <%= reply.headers_with_body.join("<br/>").html_safe %>
  </div>

  <div class="panel-footer" data-toggle="collapse"
    data-parent="#submissionOverview-<%= reply.submission.id %>"
    data-target=".replyCard[data-id='<%= reply.id %>'] .panel-body">

    Received <%= reply.content_length %> in <%= reply.response_time %>ms
    <%= reply.label_for :http_status_message, class: "pull-right" %>
    <%= reply.label_for :content_type, style: :info, class: "pull-right" %>
    <%= reply.missing_label_for :body, style: :warning, class: "pull-right" %>
    <%= reply.missing_label_for :headers, style: :danger, class: "pull-right" %>
  </div>

</div>

app/views/replies/_form.html.erb
<%= form_for(@reply, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @reply.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h4>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :destination, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :destination, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :submission, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :submission, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :http_status_code, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :http_status_code, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content_length, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :content_length, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content_type, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :content_type, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :headers, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :headers, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :processed_at, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :processed_at, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/replies/edit.html.erb
<div class="page-header">
  <%= link_to replies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @reply, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing reply</h1>
</div>

<%= render 'form' %>

app/views/replies/index.html.erb
<div class="page-header">
  <%= link_to new_reply_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Reply
  <% end %>
  <h1>Listing replies</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Destination</th>
            <th>Submission</th>
            <th>Http status code</th>
            <th>Content length</th>
            <th>Content type</th>
            <th>Headers</th>
            <th>Body</th>
            <th>Processed at</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @replies) do |reply| %>
            <td><%= reply.destination %></td>
            <td><%= reply.submission %></td>
            <td><%= reply.http_status_code %></td>
            <td><%= reply.content_length %></td>
            <td><%= reply.content_type %></td>
            <td><%= reply.headers %></td>
            <td><%= reply.body %></td>
            <td><%= reply.processed_at %></td>
            <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/replies/new.html.erb
<div class="page-header">
  <%= link_to replies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New reply</h1>
</div>

<%= render 'form' %>

app/views/replies/show.html.erb
<div class="page-header">
  <%= link_to replies_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_reply_path(@reply), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show reply</h1>
</div>

<dl class="dl-horizontal">
  <dt>Destination:</dt>
  <dd><%= @reply.destination %></dd>

  <dt>Submission:</dt>
  <dd><%= @reply.submission %></dd>

  <dt>Http status code:</dt>
  <dd><%= @reply.http_status_code %></dd>

  <dt>Content length:</dt>
  <dd><%= @reply.content_length %></dd>

  <dt>Content type:</dt>
  <dd><%= @reply.content_type %></dd>

  <dt>Headers:</dt>
  <dd><%= @reply.headers %></dd>

  <dt>Body:</dt>
  <dd><%= @reply.body %></dd>

  <dt>Processed at:</dt>
  <dd><%= @reply.processed_at %></dd>

</dl>