config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show', id: 'home'
  match 'for/:id' => 'portals#route', as: :portal_router, via: :all

  devise_for :users
  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/monitor', as: :monitor
  end

  authenticate :user do
    resources :replies
    resources :submissions
    resources :destinations
    resources :portals
  end

end

app/models/portal.rb
class Portal < ActiveRecord::Base
  acts_as_tenant :account

  belongs_to :account, counter_cache: true
  validates :account_id, presence: true

  has_many :submissions,  dependent: :destroy
  has_many :destinations, dependent: :destroy

  validates :title, presence: true
  validates :slug,  presence: true, uniqueness: true
  before_validation :generate_slug, on: :create

  def to_param
    slug
  end

  private

  def generate_slug
    self.slug = Digest::SHA512.hexdigest(SecureRandom.uuid)[25..72]
    generate_slug if self.class.find_by(slug: self.slug).present?
  end
end

app/controllers/portals_controller.rb
class PortalsController < ApplicationController
  before_action :set_portal, only: [:show, :edit, :update, :destroy]

  # GET /portals
  # GET /portals.json
  def index
    scope = current_user.portals.includes(:destinations)
    @portals = scope.all
    respond_to do |format|
      format.html
      format.json { render json: @portals }
    end
  end

  # GET /portals/1
  # GET /portals/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @portal }
    end
  end

  # GET /portals/new
  def new
    @portal = current_user.portals.build
  end

  # GET /portals/1/edit
  def edit
  end

  # POST /portals
  # POST /portals.json
  def create
    @portal = current_user.portals.new(portal_params)

    respond_to do |format|
      if @portal.save
        format.html { redirect_to @portal, notice: 'Portal was successfully created.' }
        format.json { render :show, status: :created, location: @portal }
      else
        format.html { render :new }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /portals/1
  # PATCH/PUT /portals/1.json
  def update
    respond_to do |format|
      if @portal.update(portal_params)
        format.html { redirect_to @portal, notice: 'Portal was successfully updated.' }
        format.json { render :show, status: :ok, location: @portal }
      else
        format.html { render :edit }
        format.json { render json: @portal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portals/1
  # DELETE /portals/1.json
  def destroy
    @portal.destroy
    respond_to do |format|
      format.html { redirect_to portals_url, notice: 'Portal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portal
      @portal = current_user.portals.includes(:destinations).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portal_params
      params.require(:portal).permit(:title, :slug, :destinations_count)
    end
end

app/helpers/portals_helper.rb
module PortalsHelper
end

app/views/portals/_form.html.erb
<%= form_for(@portal, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @portal.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@portal.errors.count, "error") %> prohibited this portal from being saved:</h4>

      <ul>
      <% @portal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :slug, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :slug, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :destinations_count, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :destinations_count, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/portals/edit.html.erb
<div class="page-header">
  <%= link_to portals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @portal, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing portal</h1>
</div>

<%= render 'form' %>

app/views/portals/index.html.erb
<div class="page-header">
  <%= link_to new_portal_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Portal
  <% end %>
  <h1>Listing portals</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Title</th>
            <th>Slug</th>
            <th>Destinations count</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @portals) do |portal| %>
            <td><%= portal.title %></td>
            <td><%= portal.slug %></td>
            <td><%= portal.destinations_count %></td>
            <td><%= link_to 'Show', portal %></td>
        <td><%= link_to 'Edit', edit_portal_path(portal) %></td>
        <td><%= link_to 'Destroy', portal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/portals/new.html.erb
<div class="page-header">
  <%= link_to portals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New portal</h1>
</div>

<%= render 'form' %>

app/views/portals/show.html.erb
<div class="page-header">
  <%= link_to portals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_portal_path(@portal), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show portal</h1>
</div>

<dl class="dl-horizontal">
  <dt>Title:</dt>
  <dd><%= @portal.title %></dd>

  <dt>Slug:</dt>
  <dd><%= @portal.slug %></dd>

  <dt>Destinations count:</dt>
  <dd><%= @portal.destinations_count %></dd>

</dl>