config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show', id: 'home'
  match 'for/:id' => 'portals#route', as: :portal_router, via: :all

  devise_for :users
  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/monitor', as: :monitor
  end

  authenticate :user do
    resources :replies
    resources :submissions
    resources :destinations
    resources :portals
  end

end

app/models/destination.rb
class Destination < ActiveRecord::Base
  acts_as_tenant :account

  belongs_to :account, counter_cache: true
  validates :account_id, presence: true

  belongs_to :portal, counter_cache: true
  has_many :replies, dependent: :nullify
  has_many :submissions, through: :replies

  validates :url, presence: true
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    scope = current_user.destinations.includes(:portal)
    @destinations = scope.all
    respond_to do |format|
      format.html
      format.json { render json: @destinations }
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  # def show
  #   respond_to do |format|
  #     format.html
  #     format.json { render json: @destination }
  #   end
  # end

  # GET /destinations/new
  # def new
  #   @destination = Destination.new
  # end

  # GET /destinations/1/edit
  # def edit
  # end

  # POST /destinations
  # POST /destinations.json
  # def create
  #   @destination = Destination.new(destination_params)

  #   respond_to do |format|
  #     if @destination.save
  #       format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
  #       format.json { render :show, status: :created, location: @destination }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @destination.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /destinations/1
  # # PATCH/PUT /destinations/1.json
  # def update
  #   respond_to do |format|
  #     if @destination.update(destination_params)
  #       format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @destination }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @destination.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  # def destroy
  #   @destination.destroy
  #   respond_to do |format|
  #     format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:portal_id, :url)
    end
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/_form.html.erb
<%= form_for(@destination, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @destination.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h4>

      <ul>
      <% @destination.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :portal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :portal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<div class="page-header">
  <%= link_to destinations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @destination, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing destination</h1>
</div>

<%= render 'form' %>

app/views/destinations/index.html.erb
<div class="page-header">
  <%= link_to new_destination_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Destination
  <% end %>
  <h1>Listing destinations</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Portal</th>
            <th>Url</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @destinations) do |destination| %>
            <td><%= destination.portal %></td>
            <td><%= destination.url %></td>
            <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/destinations/new.html.erb
<div class="page-header">
  <%= link_to destinations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New destination</h1>
</div>

<%= render 'form' %>

app/views/destinations/show.html.erb
<div class="page-header">
  <%= link_to destinations_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_destination_path(@destination), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show destination</h1>
</div>

<dl class="dl-horizontal">
  <dt>Portal:</dt>
  <dd><%= @destination.portal %></dd>

  <dt>Url:</dt>
  <dd><%= @destination.url %></dd>

</dl>