config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  root to: 'high_voltage/pages#show', id: 'home'
  match 'for/:id' => 'portals#route', as: :portal_router, via: :all

  devise_for :users
  authenticate :user, lambda(&:admin?) do
    mount Sidekiq::Web => '/monitor', as: :monitor
  end

  authenticate :user do
    resources :replies
    resources :submissions
    resources :destinations
    resources :portals
  end

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Web Hooker", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class='nav navbar-nav'>
        <%= navbar_link "Home", root_path %>
        <%= navbar_link "Submissions", submissions_path %>
        <%= navbar_link "Portals", portals_path %>
        <%= navbar_link "Monitor", monitor_path, target: "_blank" if current_user.try(:admin?) %>
      </ul>
      <ul class='nav navbar-nav navbar-right'>
        <% if current_user.present? %>
          <%= navbar_link 'Profile', edit_user_registration_path %>
          <%= navbar_link 'Log out', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= navbar_link 'Log in', new_user_session_path %>
          <%= navbar_link 'Register', new_user_registration_path %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Web Hooker</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Open+Sans:400,700', media: 'all' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "layouts/navbar" %>
  <div class="container-fluid">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>